package ExceptionDemo;

public class FinallyDemo {

	public static void main(String[] args) {
	try{
		int a[] = new int[5];
		a[10] = 40;
	}
	catch(Exception e){
		
		
	}finally{
		System.out.println("thank u");
	}

	}

}
